ParameterError: rename NO_ERROR to SUCCESS (#298)
to avoid conflicts with winerror.h macro

Signed-off-by: Ivan Santiago Paunovic <ivanpauno@ekumenlabs.com>